[package]
name = "integrity-scrub"
version = "0.3.1"
authors = [ "Mikael Voss <mvs@nyantec.com>" ]
edition = "2021"
description = "Scrub dm-integrity volumes"
repository = "https://github.com/illdefined/integrity-scrub"
license = "MirOS"
keywords = [ "linux", "utility", "system" ]
categories = [ "command-line-utilities" ]

[dependencies]
bytesize = "1.1"
clap = "3.0.0-beta"
libc = "0.2"
nix = "0.23"
sensitive = { version = "0.9", default-features = false }

[profile.release]
overflow-checks = true
lto = "thin"
